# Generated by Django 5.2.8 on 2025-12-14 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readstatus',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر نشاط'),
        ),
        migrations.CreateModel(
            name='InternalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_department', models.CharField(max_length=100, verbose_name='القسم المستلم')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='نص الرسالة')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوى الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
