# Generated by Django 5.2.8 on 2026-01-07 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_readstatus_options_user_last_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='internalmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.CharField(choices=[('normal', 'عادية'), ('urgent', 'عاجل'), ('immediate', 'فوري')], default='normal', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='priority',
            field=models.CharField(choices=[('normal', 'عادية'), ('urgent', 'عاجل'), ('immediate', 'فوري')], default='normal', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='readstatus',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='received_documents', to=settings.AUTH_USER_MODEL, verbose_name='مشاركة مع'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان / رقم الكتاب'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='readstatus',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='الرئيسية', max_length=100, verbose_name='القسم'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
